# Statistical Tests

In [4]:
import pandas as pd
from statTests.statSuite import StatSuite
import warnings
import os
import shutil
import pickle
from config import statistical_tests as config

pd.set_option('display.max_rows', 500)

In [6]:
config

{'input_file': '../data/output/preprocessed_data.pkl',
 'output_folder': '../data/output/statisticalTests_2022-08-02'}

This notebook calculates statistical tests (written in a own package called **'statSuite'**) of the **south african children** for the **questionary** in the SOSALL-Project.

Data have been preprocessed by Damir and have been taken without any changements in this notebook.

In [8]:
with open(config['input_file'], 'rb') as infile:
    data = pickle.load(infile)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Columns: 121 entries, PID to RNASeq
dtypes: category(3), float64(96), int64(5), object(17)
memory usage: 200.9+ KB

In [10]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
enrolement_age,217.0,22.520737,7.311254,9.000000,17.000000,22.000000,28.000000,38.000000
gender,216.0,1.444444,0.498058,1.000000,1.000000,1.000000,2.000000,2.000000
vaccination_status,215.0,1.065116,0.247307,1.000000,1.000000,1.000000,1.000000,2.000000
paracetamol_exposure,215.0,0.948837,0.220844,0.000000,1.000000,1.000000,1.000000,1.000000
paracetamol_exposure_age,201.0,4.907960,2.448517,1.000000,3.000000,4.000000,6.000000,12.000000
paracetamol_exposure_time,214.0,1.308411,0.677072,0.000000,1.000000,1.000000,2.000000,3.000000
childhood_inf_mumps,215.0,0.009302,0.096223,0.000000,0.000000,0.000000,0.000000,1.000000
childhood_inf_chickenpox,215.0,0.051163,0.220844,0.000000,0.000000,0.000000,0.000000,1.000000
childhood_inf_giandular_fever,215.0,0.009302,0.096223,0.000000,0.000000,0.000000,0.000000,1.000000
childhood_inf_tuberculosis,215.0,0.023256,0.151067,0.000000,0.000000,0.000000,0.000000,1.000000
childhood_inf_other,203.0,0.014778,0.120963,0.000000,0.000000,0.000000,0.000000,1.000000
antibiotic_exposure,214.0,0.757009,0.429895,0.000000,1.000000,1.000000,1.000000,1.000000
antibiotic_exposure_age,160.0,5.703125,2.899955,0.000000,3.000000,6.000000,8.000000,12.000000
antibiotic_exposure_courses,208.0,2.038462,0.754030,1.000000,2.000000,2.000000,2.000000,4.000000
antibiotic_exposure_last2months,213.0,0.352113,0.478754,0.000000,0.000000,0.000000,1.000000,1.000000
anti_helminthic_exposure,212.0,0.863208,0.344441,0.000000,1.000000,1.000000,1.000000,1.000000
anti_helminthic_exposure_age,182.0,12.543956,2.037153,6.000000,12.000000,12.000000,12.000000,24.000000
anti_helminthic_exposure_last,183.0,18.125683,6.106252,12.000000,12.000000,18.000000,24.000000,36.000000
anti_helminthic_exposure_yearly,212.0,0.712264,0.453779,0.000000,0.000000,1.000000,1.000000,1.000000
delivery_mode,215.0,1.325581,0.469685,1.000000,1.000000,1.000000,2.000000,2.000000
sunlight_exp_winter,210.0,2.384190,2.393340,0.000000,0.500000,1.400000,3.850000,11.000000
sunlight_exp_summer,212.0,3.835236,3.011520,0.000000,1.475000,3.000000,6.000000,12.000000
breastfeeding_ever,216.0,0.824074,0.381642,0.000000,1.000000,1.000000,1.000000,1.000000
breastfeeding_uptoage_age_complete,214.0,2.855280,2.454154,0.000000,0.372500,2.000000,6.000000,10.000000
breastfeeding_uptoage_age_stop,214.0,7.324907,7.665857,0.000000,1.000000,5.000000,12.000000,32.000000
formula_age_introduction,214.0,3.034579,2.878550,0.000000,0.000000,2.500000,6.000000,19.000000
solidfood_age_introduction,216.0,5.189815,2.090085,1.000000,4.000000,6.000000,6.000000,20.000000
solidfood_which_first,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
peanuts_exposure,215.0,0.609302,0.489045,0.000000,0.000000,1.000000,1.000000,1.000000
peanuts_exposure_age_first,130.0,14.476923,6.688200,4.000000,9.000000,12.000000,18.000000,36.000000
peanuts_exposure_regularity,132.0,0.795455,0.404906,0.000000,1.000000,1.000000,1.000000,1.000000
othernuts_exposure,215.0,0.232558,0.423449,0.000000,0.000000,0.000000,0.000000,1.000000
othernuts_exposure_age_first,50.0,14.940000,6.048815,6.000000,12.000000,12.000000,18.750000,30.000000
othernuts_exposure_regularity,50.0,0.880000,0.328261,0.000000,1.000000,1.000000,1.000000,1.000000
dairyproducts_exposure,215.0,0.990698,0.096223,0.000000,1.000000,1.000000,1.000000,1.000000
dairyproducts_exposure_age_first,213.0,7.915493,3.801985,1.000000,6.000000,7.000000,9.000000,29.000000
dairyproducts_exposure_regularity,213.0,0.981221,0.136065,0.000000,1.000000,1.000000,1.000000,1.000000
cowmilkformula_exposure,215.0,0.953488,0.211082,0.000000,1.000000,1.000000,1.000000,1.000000
cowmilkformula_exposure_age_first,203.0,3.039163,3.112655,0.000000,0.250000,2.000000,6.000000,19.000000
cowmilkformula_exposure_regularity,204.0,0.460784,0.499686,0.000000,0.000000,0.000000,1.000000,1.000000
henegg_exposure,215.0,0.874419,0.332150,0.000000,1.000000,1.000000,1.000000,1.000000
henegg_exposure_age_first,186.0,11.688172,5.090486,3.000000,8.000000,12.000000,12.000000,26.000000
henegg_exposure_regularity,188.0,0.803191,0.398648,0.000000,1.000000,1.000000,1.000000,1.000000
wheat_exposure,215.0,0.967442,0.177891,0.000000,1.000000,1.000000,1.000000,1.000000
wheat_exposure_age_first,208.0,9.985577,4.845914,1.000000,6.000000,9.500000,12.000000,27.000000
wheat_exposure_regularity,208.0,0.947115,0.224343,0.000000,1.000000,1.000000,1.000000,1.000000
fish_exposure,215.0,0.730233,0.444875,0.000000,0.000000,1.000000,1.000000,1.000000
fish_exposure_age_first,158.0,13.867089,5.319241,1.000000,12.000000,12.000000,17.000000,30.000000
fish_exposure_regularity,159.0,0.962264,0.191159,0.000000,1.000000,1.000000,1.000000,1.000000
asthma_ever,217.0,0.009217,0.095781,0.000000,0.000000,0.000000,0.000000,1.000000
hayfever_ever,217.0,0.110599,0.314360,0.000000,0.000000,0.000000,0.000000,1.000000
eczema_ever,217.0,0.552995,0.498333,0.000000,0.000000,1.000000,1.000000,1.000000
eczema_age,120.0,5.862500,4.732314,0.000000,3.000000,5.000000,7.000000,24.000000
eczema_whodiagnosed,120.0,2.916667,0.357003,1.000000,3.000000,3.000000,3.000000,3.000000
medication_any,215.0,0.009302,0.096223,0.000000,0.000000,0.000000,0.000000,1.000000
medication_nasalcorticosteroid,215.0,0.027907,0.165091,0.000000,0.000000,0.000000,0.000000,1.000000
medication_antihistamines,215.0,0.525581,0.500510,0.000000,0.000000,1.000000,1.000000,1.000000
medication_steroidcreams,215.0,0.516279,0.500901,0.000000,0.000000,1.000000,1.000000,1.000000
medication_oral_which,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
medication_antihistamines_last,113.0,2.247788,0.688308,1.000000,2.000000,2.000000,3.000000,3.000000
medicalhistory_comorbidities,215.0,0.009302,0.096223,0.000000,0.000000,0.000000,0.000000,1.000000
household_peoplelivingtogether,215.0,5.869767,2.763542,2.000000,4.000000,5.000000,7.000000,20.000000
household_otherolderchildren,214.0,1.238318,1.340671,0.000000,0.000000,1.000000,2.000000,8.000000
household_otheryoungerchildren,215.0,0.130233,0.350923,0.000000,0.000000,0.000000,0.000000,2.000000
parental_education_level,215.0,14.060465,2.500667,1.000000,13.000000,14.000000,16.000000,18.000000
parental_income,204.0,6748.916667,8469.651199,300.000000,1700.000000,3065.000000,9075.000000,60000.000000
pets_cat,215.0,0.204651,0.404388,0.000000,0.000000,0.000000,0.000000,1.000000
pets_dog,215.0,0.497674,0.501161,0.000000,0.000000,0.000000,1.000000,1.000000
farmanimal_contact_child,214.0,0.448598,0.498517,0.000000,0.000000,0.000000,1.000000,1.000000
farmanimal_contact_mother,213.0,0.469484,0.500244,0.000000,0.000000,0.000000,1.000000,1.000000
cigarettesmoke_numberofpersons,212.0,0.358491,0.641217,0.000000,0.000000,0.000000,1.000000,4.000000
cigarettesmoke_duringpregnancy,213.0,0.023474,0.151761,0.000000,0.000000,0.000000,0.000000,1.000000
am_height,217.0,82.718894,6.668698,64.000000,78.000000,83.000000,87.000000,98.000000
am_weight,217.0,12.166359,2.099762,8.100000,10.800000,12.000000,13.400000,21.200000
am_abd_girth,212.0,44.816038,4.001970,38.000000,42.000000,44.000000,47.000000,61.000000
am_skinfold,210.0,10.333333,2.172762,6.000000,9.000000,10.000000,11.000000,18.000000
bsa,113.0,19.061947,21.355425,0.000000,6.000000,11.500000,22.500000,96.000000
foodreaction_any,215.0,0.079070,0.270477,0.000000,0.000000,0.000000,0.000000,1.000000
immun_number,213.0,16.197183,1.427027,2.000000,15.000000,17.000000,17.000000,17.000000
familyhistory_mother_eczema,214.0,0.046729,0.211553,0.000000,0.000000,0.000000,0.000000,1.000000
familyhistory_mother_other_allergic_disease,214.0,0.135514,0.343074,0.000000,0.000000,0.000000,0.000000,1.000000
familyhistory_father_eczema,209.0,0.023923,0.153178,0.000000,0.000000,0.000000,0.000000,1.000000
familyhistory_father_other_allergic_disease,209.0,0.090909,0.288170,0.000000,0.000000,0.000000,0.000000,1.000000
familyhistory_sibling_eczema,90.0,0.066667,0.250841,0.000000,0.000000,0.000000,0.000000,1.000000
familyhistory_sibling_other_allergic_disease,90.0,0.088889,0.286178,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_cooking_Electricity_Gas,214.0,0.803738,0.398100,0.000000,1.000000,1.000000,1.000000,1.000000
fuel_cooking_Paraffin_Stove,214.0,0.172897,0.379045,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_cooking_Open_fires_inside,214.0,0.009346,0.096446,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_cooking_Open_fires_outside,214.0,0.233645,0.424141,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_heating_Electricity,214.0,0.182243,0.386950,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_heating_Gas,214.0,0.032710,0.178294,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_cooking_heating_Paraffin,214.0,0.640187,0.481071,0.000000,0.000000,1.000000,1.000000,1.000000
fuel_heating_Wood_Coal,214.0,0.135514,0.343074,0.000000,0.000000,0.000000,0.000000,1.000000
fuel_heating_Other,214.0,0.046729,0.211553,0.000000,0.000000,0.000000,0.000000,1.000000
log_blood_counts_wcc,187.0,2.355834,0.310605,0.963174,2.156973,2.341806,2.542386,3.160823
log_blood_counts_hb,179.0,2.401884,0.130433,1.871802,2.351375,2.397895,2.451005,3.054001
log_blood_counts_plts,178.0,5.935260,0.390909,3.786460,5.779505,5.971514,6.165628,6.735899
log_blood_counts_neutrophils,173.0,1.252668,0.498313,-0.462035,0.928219,1.255616,1.609438,2.901422
log_blood_counts_monocytes,174.0,-0.025705,0.538295,-1.660731,-0.356675,-0.010050,0.279475,2.208274
log_blood_counts_lymphocytes,173.0,1.678963,0.337726,0.488580,1.465568,1.680828,1.931521,2.569554
log_blood_counts_eosinophils,176.0,-0.700921,0.832383,-2.302585,-1.246647,-0.755023,-0.168471,2.149434

In [11]:
data.head(3)

,PID,diagnosis,location,enrolement_age,gender,vaccination_status,paracetamol_exposure,paracetamol_exposure_age,paracetamol_exposure_time,childhood_inf_mumps,...,fuel_heating_Other,log_blood_counts_wcc,log_blood_counts_hb,log_blood_counts_plts,log_blood_counts_neutrophils,log_blood_counts_monocytes,log_blood_counts_lymphocytes,log_blood_counts_eosinophils,diagnosis_location,RNASeq
0,CA-001-LS,AD,Urban,24,2.0,1.0,1.0,11.0,1.0,0.0,...,0.0,2.380472,2.442347,6.165628,1.229641,-0.162519,1.477049,0.900161,AD_Urban,no
1,CA-002-YF,AD,Urban,14,1.0,1.0,1.0,8.0,1.0,0.0,...,0.0,2.521721,2.433613,6.180224,1.269761,0.292670,1.948763,-0.174353,AD_Urban,yes
2,CA-003-US,AD,Urban,20,2.0,1.0,1.0,4.0,3.0,0.0,...,0.0,2.078191,2.388763,4.812997,0.837248,-0.713350,1.526056,-0.210721,AD_Urban,no

In [12]:
data.tail(3)

,PID,diagnosis,location,enrolement_age,gender,vaccination_status,paracetamol_exposure,paracetamol_exposure_age,paracetamol_exposure_time,childhood_inf_mumps,...,fuel_heating_Other,log_blood_counts_wcc,log_blood_counts_hb,log_blood_counts_plts,log_blood_counts_neutrophils,log_blood_counts_monocytes,log_blood_counts_lymphocytes,log_blood_counts_eosinophils,diagnosis_location,RNASeq
214,CO-151-AN,HC,Rural,23,1.0,1.0,1.0,7.0,2.0,0.0,...,0.0,2.381396,2.476538,5.835103,0.850151,0.307485,1.937302,-0.820981,HC_Rural,yes
215,CO-152-AF,HC,Rural,26,1.0,1.0,1.0,9.0,2.0,0.0,...,0.0,2.336987,2.360854,5.549465,1.278152,0.058269,1.633154,-0.198451,HC_Rural,yes
216,CO-153-YM,HC,Rural,16,2.0,1.0,1.0,5.0,2.0,0.0,...,0.0,2.233235,2.261763,6.204760,1.348073,-0.051293,1.420696,-0.385662,HC_Rural,no

Running statistical analysis for ```diagnosis```, ```location``` and its combination ```diagnosis_location```. The warnings will be disabled because there are several warnings for shapiro-test.

> UserWarning: Input data for shapiro has range zero. The results may not be accurate.
warnings.warn("Input data for shapiro has range zero."

In [13]:
try:
    os.mkdir(config['output_folder'])
    print("Directory " , config['output_folder'] ,  " Created ")
except FileExistsError:
     for filename in os.listdir(config['output_folder']):
        file_path = os.path.join(config['output_folder'], filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (file_path, e))

In [14]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for target in ['diagnosis', 'location', 'diagnosis_location']:
        obj = StatSuite(data=data, target=target, path=config['output_folder'])
        obj.run(store_csv=True)
        # obj.plot(plot_choice=['histogram'])
        os.rename(os.path.join(config['output_folder'], 'statisticalTests', 'output.csv'),
                  os.path.join(config['output_folder'], 'statisticalTests', f'statistics_{target}.csv'))
        # os.rename(os.path.join(output_folder, 'statisticalTests','plot'),
        #          os.path.join(output_folder, 'statisticalTests', f'plot_{target}'))

Successfully created the directory ../data/output/statisticalTests_2022-08-02/statisticalTests
Successfully created the directory ../data/output/statisticalTests_2022-08-02/statisticalTests/plot

## Results

The results are 3 .csv-files stored in folder ```{{output_folder}}```

In [15]:
pd.read_csv(os.path.join(config['output_folder'], 'statisticalTests', f"statistics_diagnosis.csv"))

,idx,grouped_by,grouped_levels,feature,feature_type,number_obs,normality,normality_manual,var_homogeneity,testname,p_value,p_value_adj,means,post_hoc_test,post_hoc
0,118,diagnosis,"['AD', 'HC']",diagnosis_location,category,"[116, 101]",False,False,False,chi_square,8.937300e-47,NaN,NaN,NaN,NaN
1,55,diagnosis,"['AD', 'HC']",eczema_ever,int64,"[116, 101]",False,False,False,mann_whitney,1.628551e-45,NaN,AD=1.0 / HC=0.04,NaN,NaN
2,61,diagnosis,"['AD', 'HC']",medication_steroidcreams,float64,"[114, 101]",False,False,True,mann_whitney,1.367216e-42,NaN,AD=0.956 / HC=0.02,NaN,NaN
3,60,diagnosis,"['AD', 'HC']",medication_antihistamines,float64,"[114, 101]",False,False,True,mann_whitney,1.416442e-26,NaN,AD=0.868 / HC=0.139,NaN,NaN
4,102,diagnosis,"['AD', 'HC']",fuel_cooking_Electricity_Gas,float64,"[114, 100]",False,False,False,mann_whitney,2.378413e-12,NaN,AD=0.982 / HC=0.6,NaN,NaN
5,57,diagnosis,"['AD', 'HC']",eczema_whodiagnosed,float64,"[116, 4]",False,False,False,mann_whitney,3.190624e-09,NaN,AD=2.948 / HC=2.0,NaN,NaN
6,88,diagnosis,"['AD', 'HC']",sp_fresh_egg,object,"[116, 101]",False,False,False,chi_square,1.125211e-08,NaN,NaN,NaN,NaN
7,103,diagnosis,"['AD', 'HC']",fuel_cooking_Paraffin_Stove,float64,"[114, 100]",False,False,False,mann_whitney,7.267787e-07,NaN,AD=0.053 / HC=0.31,NaN,NaN
8,68,diagnosis,"['AD', 'HC']",parental_education_level,float64,"[114, 101]",False,False,True,mann_whitney,1.165116e-06,NaN,AD=14.807 / HC=13.218,NaN,NaN
9,109,diagnosis,"['AD', 'HC']",fuel_heating_Wood_Coal,float64,"[113, 101]",False,False,False,mann_whitney,6.374473e-06,NaN,AD=0.035 / HC=0.248,NaN,NaN
10,46,diagnosis,"['HC', 'AD']",henegg_exposure_regularity,float64,"[95, 93]",False,False,False,mann_whitney,1.884541e-05,NaN,AD=0.677 / HC=0.926,NaN,NaN
11,80,diagnosis,"['AD', 'HC']",sp_egg_white,object,"[116, 101]",False,False,False,chi_square,2.492531e-05,NaN,NaN,NaN,NaN
12,79,diagnosis,"['AD', 'HC']",am_skinfold,float64,"[112, 98]",False,False,True,mann_whitney,2.787344e-05,NaN,AD=10.92 / HC=9.663,NaN,NaN
13,105,diagnosis,"['AD', 'HC']",fuel_cooking_Open_fires_outside,float64,"[114, 100]",False,False,False,mann_whitney,1.718784e-04,NaN,AD=0.132 / HC=0.35,NaN,NaN
14,92,diagnosis,"['AD', 'HC']",stool_katokatz,object,"[116, 101]",False,False,False,chi_square,1.363764e-03,NaN,NaN,NaN,NaN
15,69,diagnosis,"['AD', 'HC']",parental_income,float64,"[104, 100]",False,False,True,mann_whitney,1.907158e-03,NaN,AD=8122.212 / HC=5320.69,NaN,NaN
16,54,diagnosis,"['AD', 'HC']",hayfever_ever,int64,"[116, 101]",False,False,False,mann_whitney,1.920255e-03,NaN,AD=0.172 / HC=0.04,NaN,NaN
17,35,diagnosis,"['AD', 'HC']",othernuts_exposure,float64,"[114, 101]",False,False,False,mann_whitney,2.210112e-03,NaN,AD=0.316 / HC=0.139,NaN,NaN
18,94,diagnosis,"['AD', 'HC']",foodreaction_any,float64,"[114, 101]",False,False,False,mann_whitney,2.512074e-03,NaN,AD=0.132 / HC=0.02,NaN,NaN
19,78,diagnosis,"['AD', 'HC']",am_abd_girth,float64,"[113, 99]",False,False,True,mann_whitney,3.186959e-03,NaN,AD=45.593 / HC=43.929,NaN,NaN
20,85,diagnosis,"['AD', 'HC']",sp_peanut,object,"[116, 101]",False,False,False,chi_square,3.201638e-03,NaN,NaN,NaN,NaN
21,99,diagnosis,"['AD', 'HC']",familyhistory_father_other_allergic_disease,float64,"[112, 97]",False,False,False,mann_whitney,5.140806e-03,NaN,AD=0.143 / HC=0.031,NaN,NaN
22,76,diagnosis,"['AD', 'HC']",am_height,int64,"[116, 101]",True,False,True,t_test,6.614955e-03,NaN,AD=81.578 / HC=84.03,NaN,NaN
23,87,diagnosis,"['AD', 'HC']",sp_fresh_peanut,object,"[116, 100]",False,False,False,chi_square,9.858226e-03,NaN,NaN,NaN,NaN
24,100,diagnosis,"['AD', 'HC']",familyhistory_sibling_eczema,float64,"[45, 45]",False,False,False,mann_whitney,1.200494e-02,NaN,AD=0.133 / HC=0.0,NaN,NaN
25,96,diagnosis,"['AD', 'HC']",familyhistory_mother_eczema,float64,"[113, 101]",False,False,False,mann_whitney,1.619040e-02,NaN,AD=0.08 / HC=0.01,NaN,NaN
26,44,diagnosis,"['AD', 'HC']",henegg_exposure,float64,"[114, 101]",False,False,False,mann_whitney,1.947000e-02,NaN,AD=0.825 / HC=0.931,NaN,NaN
27,117,diagnosis,"['AD', 'HC']",log_blood_counts_eosinophils,float64,"[92, 84]",False,False,True,mann_whitney,2.228804e-02,NaN,AD=-0.55 / HC=-0.866,NaN,NaN
28,115,diagnosis,"['AD', 'HC']",log_blood_counts_monocytes,float64,"[95, 79]",False,False,True,mann_whitney,2.618964e-02,NaN,AD=0.065 / HC=-0.135,NaN,NaN
29,108,diagnosis,"['AD', 'HC']",fuel_cooking_heating_Paraffin,float64,"[113, 101]",False,False,False,mann_whitney,2.935370e-02,NaN,AD=0.708 / HC=0.564,NaN,NaN
30,98,diagnosis,"['AD', 'HC']",familyhistory_father_eczema,float64,"[112, 97]",False,False,False,mann_whitney,3.600057e-02,NaN,AD=0.045 / HC=0.0,NaN,NaN
31,49,diagnosis,"['AD', 'HC']",wheat_exposure_regularity,float64,"[108, 100]",False,False,False,mann_whitney,4.222909e-02,NaN,AD=0.917 / HC=0.98,NaN,NaN
32,6,diagnosis,"['AD', 'HC']",paracetamol_exposure_age,float64,"[109, 92]",False,False,False,mann_whitney,4.278207e-02,NaN,AD=4.518 / HC=5.37,NaN,NaN
33,84,diagnosis,"['AD', 'HC']",sp_fish,object,"[116, 101]",False,False,False,chi_square,4.289525e-02,NaN,NaN,NaN,NaN
34,50,diagnosis,"['AD', 'HC']",fish_exposure,float64,"[114, 101]",False,False,True,mann_whitney,5.520409e-02,NaN,AD=0.675 / HC=0.792,NaN,NaN
35,82,diagnosis,"['AD', 'HC']",sp_soy,object,"[116, 101]",False,False,False,chi_square,5.798994e-02,NaN,NaN,NaN,NaN
36,97,diagnosis,"['AD', 'HC']",familyhistory_mother_other_allergic_disease,float64,"[113, 101]",False,False,True,mann_whitney,6.164470e-02,NaN,AD=0.177 / HC=0.089,NaN,NaN
37,72,diagnosis,"['AD', 'HC']",farmanimal_contact_child,float64,"[113, 101]",False,False,True,mann_whitney,6.624502e-02,NaN,AD=0.389 / HC=0.515,NaN,NaN
38,71,diagnosis,"['AD', 'HC']",pets_dog,float64,"[114, 101]",False,False,True,mann_whitney,6.649162e-02,NaN,AD=0.439 / HC=0.564,NaN,NaN
39,70,diagnosis,"['AD', 'HC']",pets_cat,float64,"[114, 101]",False,False,True,mann_whitney,7.192455e-02,NaN,AD=0.158 / HC=0.257,NaN,NaN
40,22,diagnosis,"['AD', 'HC']",sunlight_exp_winter,float64,"[110, 100]",False,False,True,mann_whitney,7.770390e-02,NaN,AD=2.107 / HC=2.689,NaN,NaN
41,47,diagnosis,"['AD', 'HC']",wheat_exposure,float64,"[114, 101]",False,False,True,mann_whitney,7.938554e-02,NaN,AD=0.947 / HC=0.99,NaN,NaN
42,116,diagnosis,"['AD', 'HC']",log_blood_counts_lymphocytes,float64,"[94, 79]",False,False,True,mann_whitney,7.998032e-02,NaN,AD=1.714 / HC=1.637,NaN,NaN
43,15,diagnosis,"['AD', 'HC']",antibiotic_exposure_courses,float64,"[109, 99]",False,False,True,mann_whitney,8.457037e-02,NaN,AD=2.119 / HC=1.949,NaN,NaN
44,83,diagnosis,"['AD', 'HC']",sp_wheet,object,"[116, 101]",False,False,False,chi_square,8.654324e-02,NaN,NaN,NaN,NaN
45,111,diagnosis,"['AD', 'HC']",log_blood_counts_wcc,float64,"[100, 87]",False,False,True,mann_whitney,9.307954e-02,NaN,AD=2.39 / HC=2.317,NaN,NaN
46,23,diagnosis,"['AD', 'HC']",sunlight_exp_summer,float64,"[111, 101]",False,False,True,mann_whitney,9.531721e-02,NaN,AD=3.455 / HC=4.253,NaN,NaN
47,81,diagnosis,"['AD', 'HC']",sp_cowmilk,object,"[116, 101]",False,False,False,chi_square,1.040847e-01,NaN,NaN,NaN,NaN
48,74,diagnosis,"['AD', 'HC']",cigarettesmoke_numberofpersons,float64,"[111, 101]",False,False,False,mann_whitney,1.182891e-01,NaN,AD=0.27 / HC=0.455,NaN,NaN
49,106,diagnosis,"['AD', 'HC']",fuel_heating_Electricity,float64,"[113, 101]",False,False,True,mann_whitney,1.192996e-01,NaN,AD=0.221 / HC=0.139,NaN,NaN
50,65,diagnosis,"['AD', 'HC']",household_peoplelivingtogether,float64,"[114, 101]",False,False,True,mann_whitney,1.251316e-01,NaN,AD=5.605 / HC=6.168,NaN,NaN
51,34,diagnosis,"['AD', 'HC']",peanuts_exposure_regularity,float64,"[71, 61]",False,False,True,mann_whitney,1.296219e-01,NaN,AD=0.845 / HC=0.738,NaN,NaN
52,59,diagnosis,"['AD', 'HC']",medication_nasalcorticosteroid,float64,"[114, 101]",False,False,True,mann_whitney,1.332403e-01,NaN,AD=0.044 / HC=0.01,NaN,NaN
53,10,diagnosis,"['AD', 'HC']",childhood_inf_giandular_fever,float64,"[114, 101]",False,False,True,mann_whitney,1.337723e-01,NaN,AD=0.0 / HC=0.02,NaN,NaN
54,8,diagnosis,"['AD', 'HC']",childhood_inf_mumps,float64,"[114, 101]",False,False,True,mann_whitney,1.337723e-01,NaN,AD=0.0 / HC=0.02,NaN,NaN
55,86,diagnosis,"['AD', 'HC']",sp_hazelnut,object,"[116, 101]",False,False,False,chi_square,1.360282e-01,NaN,NaN,NaN,NaN
56,110,diagnosis,"['AD', 'HC']",fuel_heating_Other,float64,"[113, 101]",False,False,True,mann_whitney,1.407501e-01,NaN,AD=0.027 / HC=0.069,NaN,NaN
57,18,diagnosis,"['AD', 'HC']",anti_helminthic_exposure_age,float64,"[94, 88]",False,False,True,mann_whitney,1.408686e-01,NaN,AD=12.66 / HC=12.42,NaN,NaN
58,75,diagnosis,"['AD', 'HC']",cigarettesmoke_duringpregnancy,float64,"[112, 101]",False,False,True,mann_whitney,1.418916e-01,NaN,AD=0.009 / HC=0.04,NaN,NaN
59,101,diagnosis,"['AD', 'HC']",familyhistory_sibling_other_allergic_disease,float64,"[45, 45]",False,False,True,mann_whitney,1.428786e-01,NaN,AD=0.133 / HC=0.044,NaN,NaN
60,4,diagnosis,"['AD', 'HC']",vaccination_status,float64,"[114, 101]",False,False,True,mann_whitney,1.552570e-01,NaN,AD=1.088 / HC=1.04,NaN,NaN
61,89,diagnosis,"['AD', 'HC']",sp_fresh_cowmilk,object,"[116, 101]",False,False,False,chi_square,1.806743e-01,NaN,NaN,NaN,NaN
62,24,diagnosis,"['AD', 'HC']",peanuts_mother_exposure_regularity,object,"[111, 100]",False,False,False,chi_square,1.821298e-01,NaN,NaN,NaN,NaN
63,38,diagnosis,"['AD', 'HC']",dairyproducts_exposure,float64,"[114, 101]",False,False,True,mann_whitney,1.842923e-01,NaN,AD=0.982 / HC=1.0,NaN,NaN
64,104,diagnosis,"['AD', 'HC']",fuel_cooking_Open_fires_inside,float64,"[114, 100]",False,False,True,mann_whitney,1.864966e-01,NaN,AD=0.018 / HC=0.0,NaN,NaN
65,7,diagnosis,"['AD', 'HC']",paracetamol_exposure_time,float64,"[114, 100]",False,False,True,mann_whitney,2.028740e-01,NaN,AD=1.368 / HC=1.24,NaN,NaN
66,66,diagnosis,"['AD', 'HC']",household_otherolderchildren,float64,"[113, 101]",False,False,True,mann_whitney,2.029964e-01,NaN,AD=1.142 / HC=1.347,NaN,NaN
67,95,diagnosis,"['AD', 'HC']",immun_number,float64,"[113, 100]",False,False,True,mann_whitney,2.488120e-01,NaN,AD=16.168 / HC=16.23,NaN,NaN
68,5,diagnosis,"['AD', 'HC']",paracetamol_exposure,float64,"[114, 101]",False,False,True,mann_whitney,2.580416e-01,NaN,AD=0.965 / HC=0.931,NaN,NaN
69,9,diagnosis,"['AD', 'HC']",childhood_inf_chickenpox,float64,"[114, 101]",False,False,True,mann_whitney,2.580416e-01,NaN,AD=0.035 / HC=0.069,NaN,NaN
70,73,diagnosis,"['AD', 'HC']",farmanimal_contact_mother,float64,"[113, 100]",False,False,True,mann_whitney,2.666975e-01,NaN,AD=0.434 / HC=0.51,NaN,NaN
71,56,diagnosis,"['AD', 'HC']",eczema_age,float64,"[116, 4]",False,False,True,mann_whitney,2.774457e-01,NaN,AD=5.819 / HC=7.125,NaN,NaN
72,14,diagnosis,"['AD', 'HC']",antibiotic_exposure_age,float64,"[85, 75]",False,False,True,mann_whitney,2.810832e-01,NaN,AD=5.518 / HC=5.913,NaN,NaN
73,25,diagnosis,"['AD', 'HC']",peanuts_mother_exposure_avoidance,object,"[111, 99]",False,False,False,chi_square,2.878644e-01,NaN,NaN,NaN,NaN
74,43,diagnosis,"['AD', 'HC']",cowmilkformula_exposure_regularity,float64,"[107, 97]",False,False,True,mann_whitney,3.003744e-01,NaN,AD=0.495 / HC=0.423,NaN,NaN
75,26,diagnosis,"['AD', 'HC']",breastfeeding_ever,float64,"[115, 101]",False,False,True,mann_whitney,3.233474e-01,NaN,AD=0.8 / HC=0.851,NaN,NaN
76,48,diagnosis,"['AD', 'HC']",wheat_exposure_age_first,float64,"[108, 100]",False,False,True,mann_whitney,3.252216e-01,NaN,AD=9.722 / HC=10.27,NaN,NaN
77,77,diagnosis,"['AD', 'HC']",am_weight,float64,"[116, 101]",False,False,True,mann_whitney,3.379010e-01,NaN,AD=12.006 / HC=12.35,NaN,NaN
78,20,diagnosis,"['AD', 'HC']",anti_helminthic_exposure_yearly,float64,"[111, 101]",False,False,True,mann_whitney,3.543023e-01,NaN,AD=0.685 / HC=0.743,NaN,NaN
79,119,diagnosis,"['AD', 'HC']",RNASeq,object,"[116, 101]",False,False,False,chi_square,3.554208e-01,NaN,NaN,NaN,NaN
80,40,diagnosis,"['AD', 'HC']",dairyproducts_exposure_regularity,float64,"[112, 101]",False,False,True,mann_whitney,3.683340e-01,NaN,AD=0.973 / HC=0.99,NaN,NaN
81,36,diagnosis,"['AD', 'HC']",othernuts_exposure_age_first,float64,"[36, 14]",False,False,False,mann_whitney,3.722352e-01,NaN,AD=15.667 / HC=13.071,NaN,NaN
82,52,diagnosis,"['HC', 'AD']",fish_exposure_regularity,float64,"[81, 78]",False,False,True,mann_whitney,4.367548e-01,NaN,AD=0.974 / HC=0.951,NaN,NaN
83,2,diagnosis,"['AD', 'HC']",enrolement_age,int64,"[116, 101]",False,False,True,mann_whitney,4.424740e-01,NaN,AD=22.172 / HC=22.921,NaN,NaN
84,30,diagnosis,"['AD', 'HC']",solidfood_age_introduction,float64,"[115, 101]",False,False,True,mann_whitney,4.554727e-01,NaN,AD=5.209 / HC=5.168,NaN,NaN
85,16,diagnosis,"['AD', 'HC']",antibiotic_exposure_last2months,float64,"[112, 101]",False,False,True,mann_whitney,4.633313e-01,NaN,AD=0.375 / HC=0.327,NaN,NaN
86,0,diagnosis,"['AD', 'HC']",PID,object,"[116, 101]",False,False,False,chi_square,4.680756e-01,NaN,NaN,NaN,NaN
87,113,diagnosis,"['AD', 'HC']",log_blood_counts_plts,float64,"[96, 82]",False,False,True,mann_whitney,5.457862e-01,NaN,AD=5.93 / HC=5.941,NaN,NaN
88,11,diagnosis,"['AD', 'HC']",childhood_inf_tuberculosis,float64,"[114, 101]",False,False,True,mann_whitney,5.586763e-01,NaN,AD=0.018 / HC=0.03,NaN,NaN
89,12,diagnosis,"['AD', 'HC']",childhood_inf_other,float64,"[102, 101]",False,False,True,mann_whitney,5.598292e-01,NaN,AD=0.01 / HC=0.02,NaN,NaN
90,21,diagnosis,"['AD', 'HC']",delivery_mode,float64,"[114, 101]",False,False,True,mann_whitney,5.845909e-01,NaN,AD=1.342 / HC=1.307,NaN,NaN
91,67,diagnosis,"['AD', 'HC']",household_otheryoungerchildren,float64,"[114, 101]",False,False,True,mann_whitney,6.081903e-01,NaN,AD=0.123 / HC=0.139,NaN,NaN
92,63,diagnosis,"['AD', 'HC']",medication_antihistamines_last,float64,"[99, 14]",False,False,True,mann_whitney,6.098917e-01,NaN,AD=2.242 / HC=2.286,NaN,NaN
93,39,diagnosis,"['AD', 'HC']",dairyproducts_exposure_age_first,float64,"[112, 101]",False,False,True,mann_whitney,6.099280e-01,NaN,AD=8.196 / HC=7.604,NaN,NaN
94,13,diagnosis,"['AD', 'HC']",antibiotic_exposure,float64,"[113, 101]",False,False,True,mann_whitney,6.434331e-01,NaN,AD=0.77 / HC=0.743,NaN,NaN
95,41,diagnosis,"['AD', 'HC']",cowmilkformula_exposure,float64,"[114, 101]",False,False,True,mann_whitney,6.536876e-01,NaN,AD=0.947 / HC=0.96,NaN,NaN
96,32,diagnosis,"['AD', 'HC']",peanuts_exposure,float64,"[114, 101]",False,False,True,mann_whitney,6.680130e-01,NaN,AD=0.623 / HC=0.594,NaN,NaN
97,45,diagnosis,"['HC', 'AD']",henegg_exposure_age_first,float64,"[94, 92]",False,False,True,mann_whitney,7.405953e-01,NaN,AD=11.663 / HC=11.713,NaN,NaN
98,29,diagnosis,"['AD', 'HC']",formula_age_introduction,float64,"[113, 101]",False,False,True,mann_whitney,7.425369e-01,NaN,AD=2.915 / HC=3.168,NaN,NaN
99,17,diagnosis,"['AD', 'HC']",anti_helminthic_exposure,float64,"[111, 101]",False,False,True,mann_whitney,7.460070e-01,NaN,AD=0.856 / HC=0.871,NaN,NaN
100,19,diagnosis,"['AD', 'HC']",anti_helminthic_exposure_last,float64,"[95, 88]",False,False,True,mann_whitney,7.550866e-01,NaN,AD=17.947 / HC=18.318,NaN,NaN
101,37,diagnosis,"['AD', 'HC']",othernuts_exposure_regularity,float64,"[36, 14]",False,False,True,mann_whitney,7.734586e-01,NaN,AD=0.889 / HC=0.857,NaN,NaN
102,27,diagnosis,"['AD', 'HC']",breastfeeding_uptoage_age_complete,float64,"[113, 101]",False,False,True,mann_whitney,7.895922e-01,NaN,AD=2.834 / HC=2.88,NaN,NaN
103,107,diagnosis,"['AD', 'HC']",fuel_heating_Gas,float64,"[113, 101]",False,False,True,mann_whitney,8.183353e-01,NaN,AD=0.035 / HC=0.03,NaN,NaN
104,114,diagnosis,"['AD', 'HC']",log_blood_counts_neutrophils,float64,"[94, 79]",True,False,True,t_test,8.289159e-01,NaN,AD=1.245 / HC=1.262,NaN,NaN
105,51,diagnosis,"['HC', 'AD']",fish_exposure_age_first,float64,"[80, 78]",False,False,True,mann_whitney,8.313264e-01,NaN,AD=13.846 / HC=13.887,NaN,NaN
106,33,diagnosis,"['AD', 'HC']",peanuts_exposure_age_first,float64,"[70, 60]",False,False,True,mann_whitney,8.369749e-01,NaN,AD=14.4 / HC=14.567,NaN,NaN
107,28,diagnosis,"['AD', 'HC']",breastfeeding_uptoage_age_stop,float64,"[113, 101]",False,False,True,mann_whitney,8.468233e-01,NaN,AD=7.431 / HC=7.206,NaN,NaN
108,42,diagnosis,"['AD', 'HC']",cowmilkformula_exposure_age_first,float64,"[106, 97]",False,False,True,mann_whitney,8.578686e-01,NaN,AD=3.004 / HC=3.078,NaN,NaN
109,112,diagnosis,"['AD', 'HC']",log_blood_counts_hb,float64,"[97, 82]",False,False,True,mann_whitney,8.939781e-01,NaN,AD=2.398 / HC=2.406,NaN,NaN
110,53,diagnosis,"['AD', 'HC']",asthma_ever,int64,"[116, 101]",False,False,True,mann_whitney,9.269596e-01,NaN,AD=0.009 / HC=0.01,NaN,NaN
111,64,diagnosis,"['AD', 'HC']",medicalhistory_comorbidities,float64,"[114, 101]",False,False,True,mann_whitney,9.368235e-01,NaN,AD=0.009 / HC=0.01,NaN,NaN
112,58,diagnosis,"['AD', 'HC']",medication_any,float64,"[114, 101]",False,False,True,mann_whitney,9.368235e-01,NaN,AD=0.009 / HC=0.01,NaN,NaN
113,3,diagnosis,"['AD', 'HC']",gender,float64,"[115, 101]",False,False,True,mann_whitney,9.767411e-01,NaN,AD=1.443 / HC=1.446,NaN,NaN
114,1,diagnosis,"['AD', 'HC']",location,category,"[116, 101]",False,False,False,chi_square,1.000000e+00,NaN,NaN,NaN,NaN
115,93,diagnosis,"['AD', 'HC']",country,object,"[116, 101]",False,False,False,chi_square,1.000000e+00,NaN,NaN,NaN,NaN
116,31,diagnosis,"['AD', 'HC']",solidfood_which_first ERROR,float64,"[0, 0]",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
117,62,diagnosis,"['AD', 'HC']",medication_oral_which ERROR,float64,"[0, 0]",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
118,90,diagnosis,"['AD', 'HC']",scorad ERROR,object,"[116, 0]",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
119,91,diagnosis,"['AD', 'HC']",bsa ERROR,float64,"[113, 0]",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
pd.read_csv(os.path.join(config['output_folder'], 'statisticalTests', f"statistics_location.csv"))

,idx,grouped_by,grouped_levels,feature,feature_type,number_obs,normality,normality_manual,var_homogeneity,testname,p_value,p_value_adj,means,post_hoc_test,post_hoc
0,118,location,"['Rural', 'Urban']",diagnosis_location,category,"[112, 105]",False,False,False,chi_square,8.937300e-47,NaN,NaN,NaN,NaN
1,72,location,"['Rural', 'Urban']",farmanimal_contact_child,float64,"[112, 102]",False,False,False,mann_whitney,3.069327e-33,NaN,Rural=0.839 / Urban=0.02,NaN,NaN
2,73,location,"['Rural', 'Urban']",farmanimal_contact_mother,float64,"[112, 101]",False,False,False,mann_whitney,1.067841e-32,NaN,Rural=0.857 / Urban=0.04,NaN,NaN
3,22,location,"['Rural', 'Urban']",sunlight_exp_winter,float64,"[112, 98]",False,False,False,mann_whitney,1.280737e-21,NaN,Rural=3.663 / Urban=0.923,NaN,NaN
4,23,location,"['Rural', 'Urban']",sunlight_exp_summer,float64,"[112, 100]",False,False,False,mann_whitney,4.151745e-16,NaN,Rural=5.421 / Urban=2.059,NaN,NaN
5,105,location,"['Rural', 'Urban']",fuel_cooking_Open_fires_outside,float64,"[111, 103]",False,False,False,mann_whitney,8.416758e-15,NaN,Rural=0.45 / Urban=0.0,NaN,NaN
6,102,location,"['Rural', 'Urban']",fuel_cooking_Electricity_Gas,float64,"[111, 103]",False,False,False,mann_whitney,3.769758e-12,NaN,Rural=0.622 / Urban=1.0,NaN,NaN
7,103,location,"['Rural', 'Urban']",fuel_cooking_Paraffin_Stove,float64,"[111, 103]",False,False,False,mann_whitney,1.309231e-10,NaN,Rural=0.333 / Urban=0.0,NaN,NaN
8,69,location,"['Rural', 'Urban']",parental_income,float64,"[111, 93]",False,False,True,mann_whitney,2.258176e-09,NaN,Rural=5037.829 / Urban=8791.183,NaN,NaN
9,32,location,"['Rural', 'Urban']",peanuts_exposure,float64,"[112, 103]",False,False,False,mann_whitney,3.058401e-09,NaN,Rural=0.42 / Urban=0.816,NaN,NaN
10,71,location,"['Rural', 'Urban']",pets_dog,float64,"[112, 103]",False,False,True,mann_whitney,7.031309e-09,NaN,Rural=0.688 / Urban=0.291,NaN,NaN
11,109,location,"['Rural', 'Urban']",fuel_heating_Wood_Coal,float64,"[111, 103]",False,False,False,mann_whitney,2.631275e-08,NaN,Rural=0.261 / Urban=0.0,NaN,NaN
12,115,location,"['Rural', 'Urban']",log_blood_counts_monocytes,float64,"[92, 82]",False,False,True,mann_whitney,1.869037e-05,NaN,Rural=0.131 / Urban=-0.202,NaN,NaN
13,70,location,"['Rural', 'Urban']",pets_cat,float64,"[112, 103]",False,False,False,mann_whitney,4.577013e-05,NaN,Rural=0.312 / Urban=0.087,NaN,NaN
14,106,location,"['Rural', 'Urban']",fuel_heating_Electricity,float64,"[111, 103]",False,False,False,mann_whitney,7.231262e-05,NaN,Rural=0.081 / Urban=0.291,NaN,NaN
15,65,location,"['Rural', 'Urban']",household_peoplelivingtogether,float64,"[112, 103]",False,False,False,mann_whitney,2.400445e-04,NaN,Rural=6.491 / Urban=5.194,NaN,NaN
16,74,location,"['Rural', 'Urban']",cigarettesmoke_numberofpersons,float64,"[111, 101]",False,False,False,mann_whitney,5.377268e-04,NaN,Rural=0.225 / Urban=0.505,NaN,NaN
17,119,location,"['Rural', 'Urban']",RNASeq,object,"[112, 105]",False,False,False,chi_square,6.836299e-04,NaN,NaN,NaN,NaN
18,68,location,"['Rural', 'Urban']",parental_education_level,float64,"[112, 103]",False,False,True,mann_whitney,1.350840e-03,NaN,Rural=13.464 / Urban=14.709,NaN,NaN
19,66,location,"['Rural', 'Urban']",household_otherolderchildren,float64,"[112, 102]",False,False,False,mann_whitney,1.958053e-03,NaN,Rural=1.554 / Urban=0.892,NaN,NaN
20,6,location,"['Rural', 'Urban']",paracetamol_exposure_age,float64,"[108, 93]",False,False,True,mann_whitney,2.100577e-03,NaN,Rural=4.412 / Urban=5.484,NaN,NaN
21,21,location,"['Rural', 'Urban']",delivery_mode,float64,"[112, 103]",False,False,False,mann_whitney,2.362368e-03,NaN,Rural=1.232 / Urban=1.427,NaN,NaN
22,46,location,"['Rural', 'Urban']",henegg_exposure_regularity,float64,"[97, 91]",False,False,False,mann_whitney,3.077971e-03,NaN,Rural=0.887 / Urban=0.714,NaN,NaN
23,117,location,"['Rural', 'Urban']",log_blood_counts_eosinophils,float64,"[101, 75]",False,False,True,mann_whitney,4.937900e-03,NaN,Rural=-0.57 / Urban=-0.877,NaN,NaN
24,54,location,"['Rural', 'Urban']",hayfever_ever,int64,"[112, 105]",False,False,False,mann_whitney,5.816247e-03,NaN,Rural=0.054 / Urban=0.171,NaN,NaN
25,25,location,"['Rural', 'Urban']",peanuts_mother_exposure_avoidance,object,"[109, 101]",False,False,False,chi_square,6.334448e-03,NaN,NaN,NaN,NaN
26,47,location,"['Rural', 'Urban']",wheat_exposure,float64,"[112, 103]",False,False,False,mann_whitney,1.017021e-02,NaN,Rural=0.938 / Urban=1.0,NaN,NaN
27,14,location,"['Rural', 'Urban']",antibiotic_exposure_age,float64,"[90, 70]",False,False,True,mann_whitney,1.051877e-02,NaN,Rural=5.194 / Urban=6.357,NaN,NaN
28,2,location,"['Rural', 'Urban']",enrolement_age,int64,"[112, 105]",False,False,True,mann_whitney,1.171442e-02,NaN,Rural=21.295 / Urban=23.829,NaN,NaN
29,97,location,"['Rural', 'Urban']",familyhistory_mother_other_allergic_disease,float64,"[112, 102]",False,False,False,mann_whitney,1.379233e-02,NaN,Rural=0.08 / Urban=0.196,NaN,NaN
30,67,location,"['Rural', 'Urban']",household_otheryoungerchildren,float64,"[112, 103]",False,False,False,mann_whitney,1.428545e-02,NaN,Rural=0.188 / Urban=0.068,NaN,NaN
31,63,location,"['Rural', 'Urban']",medication_antihistamines_last,float64,"[61, 52]",False,False,True,mann_whitney,1.444490e-02,NaN,Rural=2.115 / Urban=2.404,NaN,NaN
32,113,location,"['Rural', 'Urban']",log_blood_counts_plts,float64,"[92, 86]",False,False,True,mann_whitney,1.531748e-02,NaN,Rural=5.868 / Urban=6.007,NaN,NaN
33,5,location,"['Rural', 'Urban']",paracetamol_exposure,float64,"[112, 103]",False,False,False,mann_whitney,2.127693e-02,NaN,Rural=0.982 / Urban=0.913,NaN,NaN
34,43,location,"['Rural', 'Urban']",cowmilkformula_exposure_regularity,float64,"[107, 97]",False,False,True,mann_whitney,3.093498e-02,NaN,Rural=0.533 / Urban=0.381,NaN,NaN
35,50,location,"['Rural', 'Urban']",fish_exposure,float64,"[112, 103]",False,False,False,mann_whitney,3.743352e-02,NaN,Rural=0.67 / Urban=0.796,NaN,NaN
36,107,location,"['Rural', 'Urban']",fuel_heating_Gas,float64,"[111, 103]",False,False,False,mann_whitney,4.388677e-02,NaN,Rural=0.009 / Urban=0.058,NaN,NaN
37,15,location,"['Rural', 'Urban']",antibiotic_exposure_courses,float64,"[110, 98]",False,False,True,mann_whitney,4.543181e-02,NaN,Rural=2.118 / Urban=1.949,NaN,NaN
38,57,location,"['Rural', 'Urban']",eczema_whodiagnosed,float64,"[61, 59]",False,False,False,mann_whitney,4.583385e-02,NaN,Rural=2.984 / Urban=2.847,NaN,NaN
39,13,location,"['Rural', 'Urban']",antibiotic_exposure,float64,"[112, 102]",False,False,False,mann_whitney,4.802113e-02,NaN,Rural=0.812 / Urban=0.696,NaN,NaN
40,17,location,"['Rural', 'Urban']",anti_helminthic_exposure,float64,"[112, 100]",False,False,True,mann_whitney,6.187937e-02,NaN,Rural=0.821 / Urban=0.91,NaN,NaN
41,12,location,"['Rural', 'Urban']",childhood_inf_other,float64,"[104, 99]",False,False,True,mann_whitney,7.534038e-02,NaN,Rural=0.0 / Urban=0.03,NaN,NaN
42,79,location,"['Rural', 'Urban']",am_skinfold,float64,"[110, 100]",False,False,True,mann_whitney,8.347611e-02,NaN,Rural=10.582 / Urban=10.06,NaN,NaN
43,36,location,"['Urban', 'Rural']",othernuts_exposure_age_first,float64,"[29, 21]",False,False,True,mann_whitney,8.659031e-02,NaN,Rural=13.286 / Urban=16.138,NaN,NaN
44,19,location,"['Rural', 'Urban']",anti_helminthic_exposure_last,float64,"[92, 91]",False,False,True,mann_whitney,8.712208e-02,NaN,Rural=17.315 / Urban=18.945,NaN,NaN
45,18,location,"['Rural', 'Urban']",anti_helminthic_exposure_age,float64,"[92, 90]",False,False,True,mann_whitney,9.688556e-02,NaN,Rural=12.424 / Urban=12.667,NaN,NaN
46,35,location,"['Rural', 'Urban']",othernuts_exposure,float64,"[112, 103]",False,False,True,mann_whitney,1.040604e-01,NaN,Rural=0.188 / Urban=0.282,NaN,NaN
47,45,location,"['Rural', 'Urban']",henegg_exposure_age_first,float64,"[95, 91]",False,False,True,mann_whitney,1.168043e-01,NaN,Rural=11.137 / Urban=12.264,NaN,NaN
48,49,location,"['Rural', 'Urban']",wheat_exposure_regularity,float64,"[105, 103]",False,False,True,mann_whitney,1.311062e-01,NaN,Rural=0.924 / Urban=0.971,NaN,NaN
49,7,location,"['Rural', 'Urban']",paracetamol_exposure_time,float64,"[111, 103]",False,False,False,mann_whitney,1.330553e-01,NaN,Rural=1.225 / Urban=1.398,NaN,NaN
50,98,location,"['Rural', 'Urban']",familyhistory_father_eczema,float64,"[111, 98]",False,False,True,mann_whitney,1.352426e-01,NaN,Rural=0.009 / Urban=0.041,NaN,NaN
51,58,location,"['Rural', 'Urban']",medication_any,float64,"[112, 103]",False,False,True,mann_whitney,1.411385e-01,NaN,Rural=0.0 / Urban=0.019,NaN,NaN
52,75,location,"['Rural', 'Urban']",cigarettesmoke_duringpregnancy,float64,"[112, 101]",False,False,True,mann_whitney,1.418916e-01,NaN,Rural=0.009 / Urban=0.04,NaN,NaN
53,3,location,"['Rural', 'Urban']",gender,float64,"[111, 105]",False,False,True,mann_whitney,1.452529e-01,NaN,Rural=1.396 / Urban=1.495,NaN,NaN
54,92,location,"['Rural', 'Urban']",stool_katokatz,object,"[112, 105]",False,False,False,chi_square,1.468544e-01,NaN,NaN,NaN,NaN
55,96,location,"['Rural', 'Urban']",familyhistory_mother_eczema,float64,"[112, 102]",False,False,True,mann_whitney,1.492848e-01,NaN,Rural=0.027 / Urban=0.069,NaN,NaN
56,76,location,"['Rural', 'Urban']",am_height,int64,"[112, 105]",True,False,True,t_test,1.513335e-01,NaN,Rural=82.089 / Urban=83.39,NaN,NaN
57,82,location,"['Rural', 'Urban']",sp_soy,object,"[112, 105]",False,False,False,chi_square,1.605271e-01,NaN,NaN,NaN,NaN
58,84,location,"['Rural', 'Urban']",sp_fish,object,"[112, 105]",False,False,False,chi_square,1.719834e-01,NaN,NaN,NaN,NaN
59,104,location,"['Rural', 'Urban']",fuel_cooking_Open_fires_inside,float64,"[111, 103]",False,False,True,mann_whitney,1.741851e-01,NaN,Rural=0.018 / Urban=0.0,NaN,NaN
60,10,location,"['Rural', 'Urban']",childhood_inf_giandular_fever,float64,"[112, 103]",False,False,True,mann_whitney,1.761248e-01,NaN,Rural=0.018 / Urban=0.0,NaN,NaN
61,8,location,"['Rural', 'Urban']",childhood_inf_mumps,float64,"[112, 103]",False,False,True,mann_whitney,1.761248e-01,NaN,Rural=0.018 / Urban=0.0,NaN,NaN
62,88,location,"['Rural', 'Urban']",sp_fresh_egg,object,"[112, 105]",False,False,False,chi_square,1.839153e-01,NaN,NaN,NaN,NaN
63,30,location,"['Rural', 'Urban']",solidfood_age_introduction,float64,"[111, 105]",False,False,True,mann_whitney,1.849169e-01,NaN,Rural=5.45 / Urban=4.914,NaN,NaN
64,77,location,"['Rural', 'Urban']",am_weight,float64,"[112, 105]",False,False,False,mann_whitney,1.857227e-01,NaN,Rural=11.944 / Urban=12.404,NaN,NaN
65,37,location,"['Urban', 'Rural']",othernuts_exposure_regularity,float64,"[29, 21]",False,False,True,mann_whitney,1.904230e-01,NaN,Rural=0.952 / Urban=0.828,NaN,NaN
66,83,location,"['Rural', 'Urban']",sp_wheet,object,"[112, 105]",False,False,False,chi_square,1.918432e-01,NaN,NaN,NaN,NaN
67,39,location,"['Rural', 'Urban']",dairyproducts_exposure_age_first,float64,"[111, 102]",False,False,True,mann_whitney,2.009552e-01,NaN,Rural=7.784 / Urban=8.059,NaN,NaN
68,4,location,"['Rural', 'Urban']",vaccination_status,float64,"[112, 103]",False,False,True,mann_whitney,2.065067e-01,NaN,Rural=1.045 / Urban=1.087,NaN,NaN
69,110,location,"['Rural', 'Urban']",fuel_heating_Other,float64,"[111, 103]",False,False,True,mann_whitney,2.421964e-01,NaN,Rural=0.063 / Urban=0.029,NaN,NaN
70,81,location,"['Rural', 'Urban']",sp_cowmilk,object,"[112, 105]",False,False,False,chi_square,2.547617e-01,NaN,NaN,NaN,NaN
71,86,location,"['Rural', 'Urban']",sp_hazelnut,object,"[112, 105]",False,False,False,chi_square,2.848828e-01,NaN,NaN,NaN,NaN
72,89,location,"['Rural', 'Urban']",sp_fresh_cowmilk,object,"[112, 105]",False,False,False,chi_square,3.217762e-01,NaN,NaN,NaN,NaN
73,16,location,"['Rural', 'Urban']",antibiotic_exposure_last2months,float64,"[111, 102]",False,False,True,mann_whitney,3.775885e-01,NaN,Rural=0.324 / Urban=0.382,NaN,NaN
74,108,location,"['Rural', 'Urban']",fuel_cooking_heating_Paraffin,float64,"[111, 103]",False,False,True,mann_whitney,3.847792e-01,NaN,Rural=0.613 / Urban=0.67,NaN,NaN
75,44,location,"['Rural', 'Urban']",henegg_exposure,float64,"[112, 103]",False,False,True,mann_whitney,4.275721e-01,NaN,Rural=0.857 / Urban=0.893,NaN,NaN
76,0,location,"['Rural', 'Urban']",PID,object,"[112, 105]",False,False,False,chi_square,4.680756e-01,NaN,NaN,NaN,NaN
77,59,location,"['Rural', 'Urban']",medication_nasalcorticosteroid,float64,"[112, 103]",False,False,True,mann_whitney,4.719948e-01,NaN,Rural=0.036 / Urban=0.019,NaN,NaN
78,52,location,"['Urban', 'Rural']",fish_exposure_regularity,float64,"[83, 76]",False,False,True,mann_whitney,4.742266e-01,NaN,Rural=0.974 / Urban=0.952,NaN,NaN
79,85,location,"['Rural', 'Urban']",sp_peanut,object,"[112, 105]",False,False,False,chi_square,4.906440e-01,NaN,NaN,NaN,NaN
80,56,location,"['Rural', 'Urban']",eczema_age,float64,"[61, 59]",False,False,True,mann_whitney,5.021136e-01,NaN,Rural=5.623 / Urban=6.11,NaN,NaN
81,100,location,"['Urban', 'Rural']",familyhistory_sibling_eczema,float64,"[48, 42]",False,False,True,mann_whitney,5.063725e-01,NaN,Rural=0.048 / Urban=0.083,NaN,NaN
82,112,location,"['Rural', 'Urban']",log_blood_counts_hb,float64,"[92, 87]",False,False,True,mann_whitney,5.195370e-01,NaN,Rural=2.412 / Urban=2.391,NaN,NaN
83,24,location,"['Rural', 'Urban']",peanuts_mother_exposure_regularity,object,"[109, 102]",False,False,False,chi_square,5.381029e-01,NaN,NaN,NaN,NaN
84,87,location,"['Rural', 'Urban']",sp_fresh_peanut,object,"[111, 105]",False,False,False,chi_square,5.388457e-01,NaN,NaN,NaN,NaN
85,90,location,"['Rural', 'Urban']",scorad,object,"[60, 56]",False,False,False,chi_square,5.399439e-01,NaN,NaN,NaN,NaN
86,28,location,"['Rural', 'Urban']",breastfeeding_uptoage_age_stop,float64,"[110, 104]",False,False,True,mann_whitney,5.456178e-01,NaN,Rural=6.704 / Urban=7.982,NaN,NaN
87,61,location,"['Rural', 'Urban']",medication_steroidcreams,float64,"[112, 103]",False,False,True,mann_whitney,5.538540e-01,NaN,Rural=0.536 / Urban=0.495,NaN,NaN
88,60,location,"['Rural', 'Urban']",medication_antihistamines,float64,"[112, 103]",False,False,True,mann_whitney,5.612140e-01,NaN,Rural=0.545 / Urban=0.505,NaN,NaN
89,11,location,"['Rural', 'Urban']",childhood_inf_tuberculosis,float64,"[112, 103]",False,False,True,mann_whitney,5.876680e-01,NaN,Rural=0.018 / Urban=0.029,NaN,NaN
90,101,location,"['Urban', 'Rural']",familyhistory_sibling_other_allergic_disease,float64,"[48, 42]",False,False,True,mann_whitney,5.938773e-01,NaN,Rural=0.071 / Urban=0.104,NaN,NaN
91,99,location,"['Rural', 'Urban']",familyhistory_father_other_allergic_disease,float64,"[111, 98]",False,False,True,mann_whitney,6.013699e-01,NaN,Rural=0.081 / Urban=0.102,NaN,NaN
92,116,location,"['Rural', 'Urban']",log_blood_counts_lymphocytes,float64,"[92, 81]",True,False,True,t_test,6.094750e-01,NaN,Rural=1.667 / Urban=1.693,NaN,NaN
93,51,location,"['Urban', 'Rural']",fish_exposure_age_first,float64,"[82, 76]",False,False,True,mann_whitney,6.437947e-01,NaN,Rural=13.553 / Urban=14.159,NaN,NaN
94,94,location,"['Rural', 'Urban']",foodreaction_any,float64,"[112, 103]",False,False,True,mann_whitney,6.674801e-01,NaN,Rural=0.071 / Urban=0.087,NaN,NaN
95,29,location,"['Rural', 'Urban']",formula_age_introduction,float64,"[109, 105]",False,False,True,mann_whitney,6.686367e-01,NaN,Rural=3.027 / Urban=3.043,NaN,NaN
96,42,location,"['Rural', 'Urban']",cowmilkformula_exposure_age_first,float64,"[106, 97]",False,False,True,mann_whitney,7.066740e-01,NaN,Rural=2.987 / Urban=3.096,NaN,NaN
97,91,location,"['Rural', 'Urban']",bsa,float64,"[59, 54]",False,False,True,mann_whitney,7.149079e-01,NaN,Rural=20.398 / Urban=17.602,NaN,NaN
98,80,location,"['Rural', 'Urban']",sp_egg_white,object,"[112, 105]",False,False,False,chi_square,7.313315e-01,NaN,NaN,NaN,NaN
99,111,location,"['Rural', 'Urban']",log_blood_counts_wcc,float64,"[100, 87]",False,False,True,mann_whitney,7.482280e-01,NaN,Rural=2.365 / Urban=2.346,NaN,NaN
100,55,location,"['Rural', 'Urban']",eczema_ever,int64,"[112, 105]",False,False,True,mann_whitney,7.996923e-01,NaN,Rural=0.545 / Urban=0.562,NaN,NaN
101,27,location,"['Rural', 'Urban']",breastfeeding_uptoage_age_complete,float64,"[110, 104]",False,False,True,mann_whitney,8.027982e-01,NaN,Rural=2.795 / Urban=2.92,NaN,NaN
102,78,location,"['Rural', 'Urban']",am_abd_girth,float64,"[110, 102]",False,False,True,mann_whitney,8.150149e-01,NaN,Rural=44.882 / Urban=44.745,NaN,NaN
103,48,location,"['Rural', 'Urban']",wheat_exposure_age_first,float64,"[105, 103]",False,False,True,mann_whitney,8.230343e-01,NaN,Rural=9.924 / Urban=10.049,NaN,NaN
104,26,location,"['Rural', 'Urban']",breastfeeding_ever,float64,"[111, 105]",False,False,True,mann_whitney,8.519648e-01,NaN,Rural=0.829 / Urban=0.819,NaN,NaN
105,34,location,"['Urban', 'Rural']",peanuts_exposure_regularity,float64,"[85, 47]",False,False,True,mann_whitney,8.649726e-01,NaN,Rural=0.787 / Urban=0.8,NaN,NaN
106,9,location,"['Rural', 'Urban']",childhood_inf_chickenpox,float64,"[112, 103]",False,False,True,mann_whitney,8.698206e-01,NaN,Rural=0.054 / Urban=0.049,NaN,NaN
107,95,location,"['Rural', 'Urban']",immun_number,float64,"[110, 103]",False,False,True,mann_whitney,8.818630e-01,NaN,Rural=16.255 / Urban=16.136,NaN,NaN
108,41,location,"['Rural', 'Urban']",cowmilkformula_exposure,float64,"[112, 103]",False,False,True,mann_whitney,8.947000e-01,NaN,Rural=0.955 / Urban=0.951,NaN,NaN
109,33,location,"['Urban', 'Rural']",peanuts_exposure_age_first,float64,"[84, 46]",False,False,True,mann_whitney,9.136030e-01,NaN,Rural=14.457 / Urban=14.488,NaN,NaN
110,40,location,"['Rural', 'Urban']",dairyproducts_exposure_regularity,float64,"[111, 102]",False,False,True,mann_whitney,9.358755e-01,NaN,Rural=0.982 / Urban=0.98,NaN,NaN
111,20,location,"['Rural', 'Urban']",anti_helminthic_exposure_yearly,float64,"[112, 100]",False,False,True,mann_whitney,9.464093e-01,NaN,Rural=0.714 / Urban=0.71,NaN,NaN
112,38,location,"['Rural', 'Urban']",dairyproducts_exposure,float64,"[112, 103]",False,False,True,mann_whitney,9.578980e-01,NaN,Rural=0.991 / Urban=0.99,NaN,NaN
113,64,location,"['Rural', 'Urban']",medicalhistory_comorbidities,float64,"[112, 103]",False,False,True,mann_whitney,9.578980e-01,NaN,Rural=0.009 / Urban=0.01,NaN,NaN
114,114,location,"['Rural', 'Urban']",log_blood_counts_neutrophils,float64,"[92, 81]",True,False,False,t_test,9.654546e-01,NaN,Rural=1.254 / Urban=1.251,NaN,NaN
115,53,location,"['Rural', 'Urban']",asthma_ever,int64,"[112, 105]",False,False,True,mann_whitney,9.687198e-01,NaN,Rural=0.009 / Urban=0.01,NaN,NaN
116,93,location,"['Rural', 'Urban']",country,object,"[112, 105]",False,False,False,chi_square,1.000000e+00,NaN,NaN,NaN,NaN
117,1,location,"['Rural', 'Urban']",diagnosis,category,"[112, 105]",False,False,False,chi_square,1.000000e+00,NaN,NaN,NaN,NaN
118,31,location,"['Rural', 'Urban']",solidfood_which_first ERROR,float64,"[0, 0]",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
119,62,location,"['Rural', 'Urban']",medication_oral_which ERROR,float64,"[0, 0]",False,False,False,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
pd.read_csv(os.path.join(config['output_folder'], 'statisticalTests', f"statistics_diagnosis_location.csv"))

,idx,grouped_by,grouped_levels,feature,feature_type,number_obs,normality,normality_manual,var_homogeneity,testname,p_value,p_value_adj,means,post_hoc_test,post_hoc
0,1,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",diagnosis,category,"[60, 56, 52, 49]",False,False,False,chi_square,8.937300e-47,NaN,NaN,NaN,NaN
1,2,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",location,category,"[60, 56, 52, 49]",False,False,False,chi_square,8.937300e-47,NaN,NaN,NaN,NaN
2,56,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",eczema_ever,int64,"[60, 56, 52, 49]",False,False,True,kruskal,2.963360e-43,NaN,AD_Urban=1.0 / AD_Rural=1.0 / HC_Urban=0.061 /...,dunn,HC_Urban <-> AD_Urban (0.0) / HC_Urban <-> AD_...
3,62,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",medication_steroidcreams,float64,"[60, 54, 52, 49]",False,False,True,kruskal,2.295044e-40,NaN,AD_Urban=0.944 / AD_Rural=0.967 / HC_Urban=0.0...,dunn,HC_Urban <-> AD_Urban (0.0) / HC_Urban <-> AD_...
4,73,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",farmanimal_contact_child,float64,"[60, 53, 52, 49]",False,False,False,kruskal,2.741084e-33,NaN,AD_Urban=0.038 / AD_Rural=0.7 / HC_Urban=0.0 /...,dunn,AD_Rural <-> AD_Urban (0.0) / HC_Urban <-> AD_...
5,74,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",farmanimal_contact_mother,float64,"[60, 53, 52, 48]",False,False,False,kruskal,5.990255e-32,NaN,AD_Urban=0.075 / AD_Rural=0.75 / HC_Urban=0.0 ...,dunn,AD_Rural <-> AD_Urban (0.0) / HC_Urban <-> AD_...
6,103,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_cooking_Electricity_Gas,float64,"[60, 54, 51, 49]",False,False,False,kruskal,1.603805e-31,NaN,AD_Urban=1.0 / AD_Rural=0.967 / HC_Urban=1.0 /...,dunn,HC_Rural <-> AD_Urban (0.0) / HC_Rural <-> AD_...
7,61,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",medication_antihistamines,float64,"[60, 54, 52, 49]",False,False,True,kruskal,3.848050e-25,NaN,AD_Urban=0.907 / AD_Rural=0.833 / HC_Urban=0.0...,dunn,HC_Urban <-> AD_Urban (0.0) / HC_Urban <-> AD_...
8,23,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",sunlight_exp_winter,float64,"[60, 52, 50, 48]",False,False,False,kruskal,7.635962e-21,NaN,AD_Urban=0.871 / AD_Rural=3.138 / HC_Urban=0.9...,dunn,AD_Rural <-> AD_Urban (0.0) / HC_Urban <-> AD_...
9,104,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_cooking_Paraffin_Stove,float64,"[60, 54, 51, 49]",False,False,False,kruskal,1.473543e-19,NaN,AD_Urban=0.0 / AD_Rural=0.1 / HC_Urban=0.0 / H...,dunn,HC_Rural <-> AD_Urban (0.0) / HC_Rural <-> AD_...
10,106,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_cooking_Open_fires_outside,float64,"[60, 54, 51, 49]",False,False,False,kruskal,2.909460e-19,NaN,AD_Urban=0.0 / AD_Rural=0.25 / HC_Urban=0.0 / ...,dunn,AD_Rural <-> AD_Urban (0.005) / HC_Urban <-> A...
11,110,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_heating_Wood_Coal,float64,"[59, 54, 52, 49]",False,False,False,kruskal,2.565486e-15,NaN,AD_Urban=0.0 / AD_Rural=0.068 / HC_Urban=0.0 /...,dunn,HC_Rural <-> AD_Urban (0.0) / HC_Rural <-> AD_...
12,24,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",sunlight_exp_summer,float64,"[60, 52, 51, 49]",False,False,False,kruskal,3.152236e-15,NaN,AD_Urban=1.987 / AD_Rural=4.702 / HC_Urban=2.1...,dunn,AD_Rural <-> AD_Urban (0.0) / HC_Urban <-> AD_...
13,70,diagnosis_location,"['AD_Rural', 'HC_Rural', 'HC_Urban', 'AD_Urban']",parental_income,float64,"[59, 52, 48, 45]",False,False,False,kruskal,4.382342e-11,NaN,AD_Urban=8989.778 / AD_Rural=7460.508 / HC_Urb...,dunn,AD_Rural <-> AD_Urban (0.009) / HC_Rural <-> A...
14,72,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",pets_dog,float64,"[60, 54, 52, 49]",False,False,False,kruskal,6.335659e-09,NaN,AD_Urban=0.296 / AD_Rural=0.567 / HC_Urban=0.2...,dunn,AD_Rural <-> AD_Urban (0.014) / HC_Urban <-> A...
15,69,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",parental_education_level,float64,"[60, 54, 52, 49]",False,False,False,kruskal,8.077703e-09,NaN,AD_Urban=14.963 / AD_Rural=14.667 / HC_Urban=1...,dunn,HC_Rural <-> AD_Urban (0.0) / HC_Rural <-> AD_...
16,33,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",peanuts_exposure,float64,"[60, 54, 52, 49]",False,False,False,kruskal,2.785225e-08,NaN,AD_Urban=0.778 / AD_Rural=0.483 / HC_Urban=0.8...,dunn,AD_Rural <-> AD_Urban (0.004) / HC_Urban <-> A...
17,47,diagnosis_location,"['AD_Rural', 'HC_Urban', 'HC_Rural', 'AD_Urban']",henegg_exposure_regularity,float64,"[50, 48, 47, 43]",False,False,False,kruskal,1.282395e-06,NaN,AD_Urban=0.535 / AD_Rural=0.8 / HC_Urban=0.875...,dunn,AD_Rural <-> AD_Urban (0.006) / HC_Urban <-> A...
18,89,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_fresh_egg,object,"[60, 56, 52, 49]",False,False,False,chi_square,1.754515e-06,NaN,NaN,NaN,NaN
19,116,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",log_blood_counts_monocytes,float64,"[50, 45, 42, 37]",False,False,True,kruskal,2.462749e-05,NaN,AD_Urban=-0.076 / AD_Rural=0.191 / HC_Urban=-0...,dunn,AD_Rural <-> AD_Urban (0.034) / HC_Urban <-> A...
20,71,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",pets_cat,float64,"[60, 54, 52, 49]",False,False,False,kruskal,7.515878e-05,NaN,AD_Urban=0.074 / AD_Rural=0.233 / HC_Urban=0.1...,dunn,HC_Rural <-> AD_Urban (0.0) / HC_Rural <-> HC_...
21,80,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",am_skinfold,float64,"[59, 53, 51, 47]",False,False,True,kruskal,1.037960e-04,NaN,AD_Urban=10.472 / AD_Rural=11.322 / HC_Urban=9...,dunn,HC_Urban <-> AD_Rural (0.0) / HC_Rural <-> AD_...
22,109,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_cooking_heating_Paraffin,float64,"[59, 54, 52, 49]",False,False,True,kruskal,1.116667e-04,NaN,AD_Urban=0.611 / AD_Rural=0.797 / HC_Urban=0.7...,dunn,HC_Rural <-> AD_Rural (0.0) / HC_Rural <-> HC_...
23,55,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",hayfever_ever,int64,"[60, 56, 52, 49]",False,False,False,kruskal,1.644148e-04,NaN,AD_Urban=0.268 / AD_Rural=0.083 / HC_Urban=0.0...,dunn,AD_Rural <-> AD_Urban (0.006) / HC_Urban <-> A...
24,107,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_heating_Electricity,float64,"[59, 54, 52, 49]",False,False,False,kruskal,2.863251e-04,NaN,AD_Urban=0.352 / AD_Rural=0.102 / HC_Urban=0.2...,dunn,AD_Rural <-> AD_Urban (0.003) / HC_Rural <-> A...
25,66,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",household_peoplelivingtogether,float64,"[60, 54, 52, 49]",False,False,True,kruskal,1.061925e-03,NaN,AD_Urban=5.019 / AD_Rural=6.133 / HC_Urban=5.3...,dunn,HC_Rural <-> AD_Urban (0.001) / HC_Rural <-> H...
26,75,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",cigarettesmoke_numberofpersons,float64,"[59, 52, 52, 49]",False,False,False,kruskal,2.132619e-03,NaN,AD_Urban=0.385 / AD_Rural=0.169 / HC_Urban=0.6...,dunn,HC_Urban <-> AD_Rural (0.002) / HC_Rural <-> H...
27,118,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",log_blood_counts_eosinophils,float64,"[54, 47, 38, 37]",False,False,True,kruskal,2.312926e-03,NaN,AD_Urban=-0.612 / AD_Rural=-0.507 / HC_Urban=-...,dunn,HC_Urban <-> AD_Rural (0.001) / HC_Rural <-> H...
28,36,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",othernuts_exposure,float64,"[60, 54, 52, 49]",False,False,False,kruskal,2.660131e-03,NaN,AD_Urban=0.407 / AD_Rural=0.233 / HC_Urban=0.1...,dunn,HC_Urban <-> AD_Urban (0.008) / HC_Rural <-> A...
29,7,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",paracetamol_exposure_age,float64,"[57, 52, 51, 41]",False,False,True,kruskal,2.818321e-03,NaN,AD_Urban=5.01 / AD_Rural=4.07 / HC_Urban=6.085...,dunn,HC_Urban <-> AD_Rural (0.001)
30,119,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",RNASeq,object,"[60, 56, 52, 49]",False,False,False,chi_square,3.010400e-03,NaN,NaN,NaN,NaN
31,15,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",antibiotic_exposure_age,float64,"[48, 42, 37, 33]",False,False,True,kruskal,4.655413e-03,NaN,AD_Urban=6.757 / AD_Rural=4.562 / HC_Urban=5.9...,dunn,AD_Rural <-> AD_Urban (0.004)
32,93,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",stool_katokatz,object,"[60, 56, 52, 49]",False,False,False,chi_square,4.841729e-03,NaN,NaN,NaN,NaN
33,48,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",wheat_exposure,float64,"[60, 54, 52, 49]",False,False,False,kruskal,6.229177e-03,NaN,AD_Urban=1.0 / AD_Rural=0.9 / HC_Urban=1.0 / H...,dunn,AD_Rural <-> AD_Urban (0.016) / HC_Urban <-> A...
34,6,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",paracetamol_exposure,float64,"[60, 54, 52, 49]",False,False,False,kruskal,7.914932e-03,NaN,AD_Urban=0.963 / AD_Rural=0.967 / HC_Urban=0.8...,dunn,HC_Rural <-> HC_Urban (0.007)
35,67,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",household_otherolderchildren,float64,"[60, 53, 52, 49]",False,False,True,kruskal,9.969739e-03,NaN,AD_Urban=0.792 / AD_Rural=1.45 / HC_Urban=1.0 ...,dunn,HC_Rural <-> AD_Urban (0.011)
36,51,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fish_exposure,float64,"[60, 54, 52, 49]",False,False,False,kruskal,1.039678e-02,NaN,AD_Urban=0.796 / AD_Rural=0.567 / HC_Urban=0.7...,dunn,AD_Rural <-> AD_Urban (0.036) / HC_Urban <-> A...
37,81,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_egg_white,object,"[60, 56, 52, 49]",False,False,False,chi_square,1.155071e-02,NaN,NaN,NaN,NaN
38,98,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",familyhistory_mother_other_allergic_disease,float64,"[60, 53, 52, 49]",False,False,False,kruskal,1.841545e-02,NaN,AD_Urban=0.226 / AD_Rural=0.133 / HC_Urban=0.1...,dunn,HC_Rural <-> AD_Urban (0.012)
39,22,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",delivery_mode,float64,"[60, 54, 52, 49]",False,False,False,kruskal,2.236688e-02,NaN,AD_Urban=1.444 / AD_Rural=1.25 / HC_Urban=1.40...,dunn,NaN
40,95,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",foodreaction_any,float64,"[60, 54, 52, 49]",False,False,False,kruskal,2.299872e-02,NaN,AD_Urban=0.148 / AD_Rural=0.117 / HC_Urban=0.0...,dunn,NaN
41,26,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",peanuts_mother_exposure_avoidance,object,"[57, 54, 52, 47]",False,False,False,chi_square,2.407425e-02,NaN,NaN,NaN,NaN
42,77,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",am_height,int64,"[60, 56, 52, 49]",False,False,True,kruskal,2.519669e-02,NaN,AD_Urban=82.0 / AD_Rural=81.183 / HC_Urban=84....,dunn,HC_Urban <-> AD_Rural (0.026)
43,79,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",am_abd_girth,float64,"[58, 55, 52, 47]",False,False,False,kruskal,3.209695e-02,NaN,AD_Urban=45.436 / AD_Rural=45.741 / HC_Urban=4...,dunn,NaN
44,97,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",familyhistory_mother_eczema,float64,"[60, 53, 52, 49]",False,False,False,kruskal,3.601699e-02,NaN,AD_Urban=0.113 / AD_Rural=0.05 / HC_Urban=0.02...,dunn,HC_Rural <-> AD_Urban (0.037)
45,99,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",familyhistory_father_eczema,float64,"[59, 53, 52, 45]",False,False,False,kruskal,3.688900e-02,NaN,AD_Urban=0.075 / AD_Rural=0.017 / HC_Urban=0.0...,dunn,NaN
46,100,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",familyhistory_father_other_allergic_disease,float64,"[59, 53, 52, 45]",False,False,False,kruskal,4.387064e-02,NaN,AD_Urban=0.151 / AD_Rural=0.136 / HC_Urban=0.0...,dunn,NaN
47,83,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_soy,object,"[60, 56, 52, 49]",False,False,False,chi_square,4.479005e-02,NaN,NaN,NaN,NaN
48,85,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_fish,object,"[60, 56, 52, 49]",False,False,False,chi_square,4.529200e-02,NaN,NaN,NaN,NaN
49,53,diagnosis_location,"['AD_Urban', 'HC_Rural', 'HC_Urban', 'AD_Rural']",fish_exposure_regularity,float64,"[43, 41, 40, 35]",False,False,False,kruskal,4.860434e-02,NaN,AD_Urban=1.0 / AD_Rural=0.943 / HC_Urban=0.9 /...,dunn,NaN
50,86,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_peanut,object,"[60, 56, 52, 49]",False,False,False,chi_square,5.285434e-02,NaN,NaN,NaN,NaN
51,45,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",henegg_exposure,float64,"[60, 54, 52, 49]",False,False,True,kruskal,5.458296e-02,NaN,AD_Urban=0.815 / AD_Rural=0.833 / HC_Urban=0.9...,NaN,NaN
52,101,diagnosis_location,"['HC_Urban', 'AD_Urban', 'AD_Rural', 'HC_Rural']",familyhistory_sibling_eczema,float64,"[25, 23, 22, 20]",False,False,True,kruskal,5.533085e-02,NaN,AD_Urban=0.174 / AD_Rural=0.091 / HC_Urban=0.0...,NaN,NaN
53,3,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",enrolement_age,int64,"[60, 56, 52, 49]",False,False,True,kruskal,7.168892e-02,NaN,AD_Urban=23.375 / AD_Rural=21.05 / HC_Urban=24...,NaN,NaN
54,84,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_wheet,object,"[60, 56, 52, 49]",False,False,False,chi_square,7.318399e-02,NaN,NaN,NaN,NaN
55,16,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",antibiotic_exposure_courses,float64,"[59, 51, 50, 48]",False,False,True,kruskal,7.439379e-02,NaN,AD_Urban=2.04 / AD_Rural=2.186 / HC_Urban=1.85...,NaN,NaN
56,44,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",cowmilkformula_exposure_regularity,float64,"[56, 51, 51, 46]",False,False,True,kruskal,8.032786e-02,NaN,AD_Urban=0.451 / AD_Rural=0.536 / HC_Urban=0.3...,NaN,NaN
57,50,diagnosis_location,"['AD_Urban', 'AD_Rural', 'HC_Rural', 'HC_Urban']",wheat_exposure_regularity,float64,"[54, 54, 51, 49]",False,False,True,kruskal,8.742509e-02,NaN,AD_Urban=0.944 / AD_Rural=0.889 / HC_Urban=1.0...,NaN,NaN
58,114,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",log_blood_counts_plts,float64,"[50, 46, 42, 40]",False,False,True,kruskal,8.972625e-02,NaN,AD_Urban=6.005 / AD_Rural=5.861 / HC_Urban=6.0...,NaN,NaN
59,68,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",household_otheryoungerchildren,float64,"[60, 54, 52, 49]",False,False,True,kruskal,9.758528e-02,NaN,AD_Urban=0.056 / AD_Rural=0.183 / HC_Urban=0.0...,NaN,NaN
60,11,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",childhood_inf_giandular_fever,float64,"[60, 54, 52, 49]",False,False,True,kruskal,9.795001e-02,NaN,AD_Urban=0.0 / AD_Rural=0.0 / HC_Urban=0.0 / H...,NaN,NaN
61,9,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",childhood_inf_mumps,float64,"[60, 54, 52, 49]",False,False,True,kruskal,9.795001e-02,NaN,AD_Urban=0.0 / AD_Rural=0.0 / HC_Urban=0.0 / H...,NaN,NaN
62,19,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Urban', 'HC_Rural']",anti_helminthic_exposure_age,float64,"[48, 46, 44, 44]",False,False,True,kruskal,9.802129e-02,NaN,AD_Urban=12.891 / AD_Rural=12.438 / HC_Urban=1...,NaN,NaN
63,88,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_fresh_peanut,object,"[60, 56, 51, 49]",False,False,False,chi_square,1.162697e-01,NaN,NaN,NaN,NaN
64,82,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_cowmilk,object,"[60, 56, 52, 49]",False,False,False,chi_square,1.244590e-01,NaN,NaN,NaN,NaN
65,8,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",paracetamol_exposure_time,float64,"[60, 54, 51, 49]",False,False,False,kruskal,1.272082e-01,NaN,AD_Urban=1.519 / AD_Rural=1.233 / HC_Urban=1.2...,NaN,NaN
66,105,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_cooking_Open_fires_inside,float64,"[60, 54, 51, 49]",False,False,True,kruskal,1.606177e-01,NaN,AD_Urban=0.0 / AD_Rural=0.033 / HC_Urban=0.0 /...,NaN,NaN
67,60,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",medication_nasalcorticosteroid,float64,"[60, 54, 52, 49]",False,False,True,kruskal,1.668238e-01,NaN,AD_Urban=0.019 / AD_Rural=0.067 / HC_Urban=0.0...,NaN,NaN
68,87,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_hazelnut,object,"[60, 56, 52, 49]",False,False,False,chi_square,1.681160e-01,NaN,NaN,NaN,NaN
69,5,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",vaccination_status,float64,"[60, 54, 52, 49]",False,False,True,kruskal,1.735630e-01,NaN,AD_Urban=1.13 / AD_Rural=1.05 / HC_Urban=1.041...,NaN,NaN
70,117,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",log_blood_counts_lymphocytes,float64,"[50, 44, 42, 37]",False,False,True,kruskal,1.845206e-01,NaN,AD_Urban=1.7 / AD_Rural=1.726 / HC_Urban=1.684...,NaN,NaN
71,76,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",cigarettesmoke_duringpregnancy,float64,"[60, 52, 52, 49]",False,False,True,kruskal,2.079805e-01,NaN,AD_Urban=0.019 / AD_Rural=0.0 / HC_Urban=0.061...,NaN,NaN
72,108,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_heating_Gas,float64,"[59, 54, 52, 49]",False,False,True,kruskal,2.259602e-01,NaN,AD_Urban=0.056 / AD_Rural=0.017 / HC_Urban=0.0...,NaN,NaN
73,90,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",sp_fresh_cowmilk,object,"[60, 56, 52, 49]",False,False,False,chi_square,2.325506e-01,NaN,NaN,NaN,NaN
74,14,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",antibiotic_exposure,float64,"[60, 53, 52, 49]",False,False,True,kruskal,2.418557e-01,NaN,AD_Urban=0.717 / AD_Rural=0.817 / HC_Urban=0.6...,NaN,NaN
75,18,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",anti_helminthic_exposure,float64,"[60, 52, 51, 49]",False,False,True,kruskal,2.497345e-01,NaN,AD_Urban=0.922 / AD_Rural=0.8 / HC_Urban=0.898...,NaN,NaN
76,111,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",fuel_heating_Other,float64,"[59, 54, 52, 49]",False,False,True,kruskal,2.673123e-01,NaN,AD_Urban=0.0 / AD_Rural=0.051 / HC_Urban=0.061...,NaN,NaN
77,13,diagnosis_location,"['AD_Rural', 'HC_Rural', 'AD_Urban', 'HC_Urban']",childhood_inf_other,float64,"[52, 52, 50, 49]",False,False,True,kruskal,2.706882e-01,NaN,AD_Urban=0.02 / AD_Rural=0.0 / HC_Urban=0.041 ...,NaN,NaN
78,43,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",cowmilkformula_exposure_age_first,float64,"[55, 51, 51, 46]",False,False,True,kruskal,2.813803e-01,NaN,AD_Urban=3.578 / AD_Rural=2.471 / HC_Urban=2.5...,NaN,NaN
79,37,diagnosis_location,"['AD_Urban', 'AD_Rural', 'HC_Urban', 'HC_Rural']",othernuts_exposure_age_first,float64,"[22, 14, 7, 7]",False,False,False,kruskal,2.828613e-01,NaN,AD_Urban=16.682 / AD_Rural=14.071 / HC_Urban=1...,NaN,NaN
80,28,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",breastfeeding_uptoage_age_complete,float64,"[58, 55, 52, 49]",False,False,True,kruskal,3.007230e-01,NaN,AD_Urban=3.215 / AD_Rural=2.472 / HC_Urban=2.5...,NaN,NaN
81,112,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Rural', 'HC_Urban']",log_blood_counts_wcc,float64,"[53, 47, 47, 40]",False,False,True,kruskal,3.157053e-01,NaN,AD_Urban=2.364 / AD_Rural=2.413 / HC_Urban=2.3...,NaN,NaN
82,35,diagnosis_location,"['HC_Urban', 'AD_Urban', 'AD_Rural', 'HC_Rural']",peanuts_exposure_regularity,float64,"[43, 42, 29, 18]",False,False,True,kruskal,3.647955e-01,NaN,AD_Urban=0.833 / AD_Rural=0.862 / HC_Urban=0.7...,NaN,NaN
83,20,diagnosis_location,"['AD_Rural', 'AD_Urban', 'HC_Urban', 'HC_Rural']",anti_helminthic_exposure_last,float64,"[48, 47, 44, 44]",False,False,True,kruskal,3.708159e-01,NaN,AD_Urban=18.979 / AD_Rural=16.938 / HC_Urban=1...,NaN,NaN

## building .html and storing files

In [18]:
os.system('jupyter nbconvert --to html statistical_tests.ipynb')
os.rename(os.path.join(os.getcwd(), 'statistical_tests.html'),
          os.path.abspath(os.path.join(config['output_folder'], 'statisticalTests', 'statistical_tests.html')))

[NbConvertApp] Converting notebook statistical_tests.ipynb to html
[NbConvertApp] Writing 625483 bytes to statistical_tests.html